name: Deploy Website

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-website.yml"
      - "website/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Bun
      - uses: oven-sh/setup-bun@v2

      # Setup GitHub Pages
      - uses: actions/configure-pages@v5

      # Install dependencies (masuk ke folder docs)
      - name: Install dependencies
        run: |
          cd website/docs
          bun install

      # Build VitePress (dari folder docs)
      - name: Build Website
        run: |
          cd website/docs
          bun run build
          touch .vitepress/dist/.nojekyll

      # Upload hasil build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: website/docs/.vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment